apiVersion: v1
kind: Secret
metadata:
  name: _COMMON-secret
  labels:
    app: wordpress
    layer: secret
data:
  MYSQL_ROOT_PASSWORD: _MYSQL_ROOT_PASSWORD
  MYSQL_DATABASE: _MYSQL_DATABASE
  MYSQL_USER: _MYSQL_USER
  MYSQL_PASSWORD: _MYSQL_PASSWORD
